# Site Settings
baseurl: ""
url : "https://j1c.me"

# Blog Settings
theme_settings :
  title : Jaewon Chung
  favicon : assets/favicon.png

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : Jaewon Chung
    description : "{Neuro, Data} Scientist • Biomedical Engineering PhD Student at Johns Hopkins University"

  # Icons
  icons :
    email: j1c@jhu.edu
    linkedin:  # Full URL 
    github: j1c
    gitlab: 
    bitbucket: 
    google_plus:
    twitter: j1chung
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname : j1c

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
