# Site Settings
baseurl: ""
url : "https://j1c.me"

# Blog Settings
theme_settings :
  title : Jaewon Chung
  favicon : assets/favicon.png

  # Icons
  icons :
    email: j1c@jhu.edu
    linkedin:  # Full URL 
    github: j1c
    gitlab: 
    bitbucket: 
    google_plus:
    twitter: j1chung
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname : j1c

# Conversion
markdown: kramdown
incremental: false
excerpt_separator: "\n"

# Markdown Processing
kramdown:
  input: GFM

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate]
bootstrap:
  assets: true
